language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: '9.6'
notifications:
  email:
    on_success: never
    on_failure: never
cache:
- bundler
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: riWsrbmSUigAeOSbG26XhqJqlkck+O7KGeWeG9nTxvmBZOhKTPs1YN13NHUdvsXOkoVYSfB9h+kvak92mMYe79VLLA0g7bw5eSDw39bJSAie4FIklVLab7s/tq0d/IbN+4LpjgMcEdkl/seyKrEADJDyuq9+cIEs/nXKi7s8KD1+oUkpLkDLSGB4dmZ6TVFK6iW3Nabu0R7AdlvjZD8ePfZK6Iwze+MuAcbI1FFJyydMHuAS0h0UWyJ0rh0eF6n2mb00ZRPxicGoPRFyfrjfwrRF86twnerLFOrtRzRdkcg2MbJf5IwY/z4PCoxOf0JPf53PbTwj0rscyYch1zvN4hKPZS3tLYMWsCoaFbgMwOWMHlYWCmW68WNb3Y7H+dfpYo1B9Fw4mp8PfgB7Se+10TSFNBwcGGxtEXrNcPOaaFC3jJorsHGL8j165ziTSCcn6mLp7eEfT6tio209I+eTiuB3U79pV3b8Hc6ZoXXN4vIJG9U6000nyDfPTbA21QpuVwdRsNRSmMOVdy70KCOW3WI9LGKJcM2mU+y1UoRxU/CmBDXeROsRKdMTRtm9V0dycL9PAraeyQKyLaDf6eFhwKUrEjjCUr9qeqdYbIpxwViR8rgat0uIIgGlD+GIhwgiV1maQSuMKnTYPcc7U9D44lX4g+3uxziKO8R7UON+Jus=
  app: sweater-weather-ag
  on:
    repo: AngelaGuardia/sweater_weather
    branch: main
  skip_cleanup: 'true'
