language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: '9.6'
notifications:
  email:
    on_success: never
    on_failure: never
cache:
- bundler
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: hsDWoFhuF99Vmz02KXEmf4cvedDVe4GlL52xKaAMuHJHsNLl1EzKyX2mTWWh40tT4P99PckhkMl5TZttYgPRSD5vFap5f3hFfAQOMoahMr/MdZKB2dx4ZYv1+/2jREcj4swmNxb1wkLgwWi/m4HRzP/xxfEYkK65lpRWL4Ri0iRu6PX4/Se1i6VDfJkDLZPMUsFRGiJEMXYUFPd8HM+2uDpaOrrReKezCn06FmpyKkxpkjaxmSy/+XNkQ31Q0qGcRgJIsPPHRJRE4xymqfi/WSzAnpbCjP/TgXE+4OGehJ2uodkBibxRJOSJVtlT2TgQ3B3YoczCm7uPs+eDlQ8o8Fe1lQgCP5oYpoNxBFGdPdTqvuWGXnLnryzW8kVEaWHTjxPS7znpiY9mbhPdRMcZ6PALOxBQ6zw5OY3MiKxy6ZxFfGY9v7iDRb6M+avgzHBJXjoMJgwjB8xq289YTbqH5kXAXZv5liaZe2RqPNsvflxX2UwgkfPjJCEujvBRzj/9NRNyuXbyP0WjeUAuXlevZVym6dhayTrkTqPYXd2I4IL1RWIplKUec3yUOhJL/729CMg14E9ZL+L4shTlxEc2CA1ZIWzEhvN0O9drwzinMoXBLtVSi88AlTTjAEQxSoILJ011vb32Db/1WbAmNCxTKEiBbjWiTAApindKmWalhcg=
  app: sweater-weather-ag
  on:
    repo: AngelaGuardia/sweater_weather
    branch: main
  skip_cleanup: 'true'
