language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: '9.6'
notifications:
  email:
    on_success: never
    on_failure: never
cache:
- bundler
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: hFiiWk6xVzgTafFz/JfEF9vmPjRGGG3p0gAnnvJsaCETwxaWGaWFQ9AEF4b7pwzvX6iBq89Mies6SLJ1P488vSgkdSla+ShBwIfaTWlQTDD+pNnS8s2E1KolZukbkLjzJrpwAjFJGBZNTzAkG0lyU9pIuQ8KWhbbFVYu54+8v7D8re/fXXq6SZMuRhK4zfEAYK226W/1DLt9efCdVjUN+D70f8+jv5nW5zT8KQwmLCdEAW2bDpEtuBGEuD3dYKTv2Hvoo0SBuG3270BZ2tmiLInv1eX93xJ2kP8MyX9iyeeSn3OBezEslIMj5RzA73UvITMi5DlRS4VvJJ/NZOkumTdLavF7yz3n3/sVMeY7oy7tutnZC79gsAj7raXQeV6WK34yH52hR2X8QWhyGXjAZW9tezy5TkbBVXibJbYzOtp/cLQMD5hYZ9WrmuqXe/eAYti68968NQ8L1ItTkPlZhCVbGuCNCzGdU/Uzdrimln7zr52NiY/2mH67Zhe45aSAKfjsS7+YPn+fALLXUOWkKf5QMz7WbaNnBL7M6lsLpCCC+ZW00fwqz+KQxj/GTmci/LBHxE2agUXa+VXMsm/6AS2cxXx3Ro04U7FsWf577wMLABqEGpsX6gjtLG+aKI8KH9NdUEbon0djpdzXQH+Y0MCvB1YyC6DyzIk7nOhyr5g=
  app: sweater-weather-ag
  on:
    repo: AngelaGuardia/sweater_weather
    branch: main
  skip_cleanup: 'true'
